# .github/workflows/run-agent.yml (FINAL, PERFECTED, GOOGLE MULTI-KEY)

name: 'Run AI Agent'

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: read

jobs:
  run-agent-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AGENT_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the AI Agent
        run: node server.js
        env:
          # === GOOGLE MULTI-KEY ENV ===
          GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY_1 }}
          GEMINI_API_KEY_2: ${{ secrets.GEMINI_API_KEY_2 }}
          GEMINI_API_KEY_3: ${{ secrets.GEMINI_API_KEY_3 }}
          GEMINI_API_KEY_4: ${{ secrets.GEMINI_API_KEY_4 }}
          GEMINI_API_KEY_5: ${{ secrets.GEMINI_API_KEY_5 }}
          GEMINI_API_KEY_6: ${{ secrets.GEMINI_API_KEY_6 }}
          GEMINI_API_KEY_7: ${{ secrets.GEMINI_API_KEY_7 }}
          GEMINI_API_KEY_8: ${{ secrets.GEMINI_API_KEY_8 }}
          GEMINI_API_KEY_9: ${{ secrets.GEMINI_API_KEY_9 }}
          GEMINI_API_KEY_10: ${{ secrets.GEMINI_API_KEY_10 }}
          
          AGENT_GITHUB_TOKEN: ${{ secrets.AGENT_GITHUB_TOKEN }}
          AGENT_GOAL: ${{ github.event.issue.body }}
